/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
    	
//    	Car car = new Car("引擎", "轮子");
//        System.out.println(car.start());
        
    	SportsCar sportsCar = new SportsCar("引擎", "轮子","车灯");
        System.out.println(sportsCar.startSportsCar());
        System.out.println(sportsCar.speedOn());
        
        Truck truck = new Truck("引擎", "轮子","负载车厢");
        System.out.println(truck.load());
        
        // story 4 将Car改为抽象类，这样Car本身就不能实例化，但是Car的继承类SportsCar和Truck依然可以。
        
    }
    
}
